version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: top100
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MYSQL_URL=mysql+pymysql://user:pass@mysql:3306/top100
      - TZ=America/Toronto
      - API_TOKEN=changeme
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8000:8000'
    volumes:
      - ./data:/app/data

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - '8501:8501'
    volumes:
      - ./data:/app/data

volumes:
  mysql_data:
