[tool.black]
line-length = 88
target-version = ['py311']

[tool.flake8]
max-line-length = 88
extend-ignore = ['E203']

[tool.pytest.ini_options]
minversion = '6.0'
addopts = '--cov=barchart_swing_bot --cov-report=term-missing'
pythonpath = ['.']
